"""
Grievance Assistance & Complaint Preparation Router.

POST /api/grievance
  → Accepts grievance details, creates draft record, generates structured summary & official advice.

GET /api/grievance/{id}
  → Retrieve grievance details by UUID.

GET /api/grievance/{id}/summary
  → Retrieve structured complaint summary and verification guidelines.
"""
from __future__ import annotations
import os
import sys
import logging
import secrets
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))
))))

from database.repository import (
    create_grievance,
    get_grievance,
    mask_citizen_name,
    mask_citizen_phone,
)
from app.providers.bhashini_provider import BhashiniProvider
from app.schemas.grievance_handoff import (
    HandoffCreateRequest,
    HandoffResponse,
    AssistanceSlipData,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/grievance", tags=["grievance"])

FACILITATION_DISCLAIMER = (
    "This is a facilitation slip generated by SahkaarSetu for assistance at the local PACS desk. "
    "It is not a court summons, registrar order, or confirmation of official filing."
)


def _generate_pacs_reference_code() -> str:
    """Deterministic human-readable unique reference code (e.g. PACS-2026-X8K9M2)."""
    alphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"
    suffix = "".join(secrets.choice(alphabet) for _ in range(6))
    return f"PACS-2026-{suffix}"


class GrievanceCreateRequest(BaseModel):
    description: str = Field(
        ...,
        min_length=5,
        max_length=4000,
        description="Detailed description of the cooperative grievance or dispute.",
    )
    category: Optional[str] = Field(
        default="GRIEVANCE",
        description="Grievance category e.g. PACS, Crop Insurance, Loan, Society Election, Management.",
    )
    language: str = Field(
        default="en",
        description="ISO language code: en | hi | mr",
    )
    conversation_id: Optional[str] = Field(
        default=None,
        description="Optional conversation UUID associated with this grievance.",
    )


class GrievanceSummaryResponse(BaseModel):
    grievance_id: str
    category: str
    description: str
    summary: str
    status: str
    suggested_next_steps: list[str]
    disclaimer: str
    source_url: str


@router.post("", response_model=GrievanceSummaryResponse, status_code=status.HTTP_201_CREATED)
async def submit_grievance_assistance(body: GrievanceCreateRequest) -> GrievanceSummaryResponse:
    """
    Generate structured complaint summary and store a draft grievance record.

    NOTE: This system prepares a structured grievance summary for official submission.
    It DOES NOT execute automated official government filing.
    """
    try:
        cat = body.category or "GRIEVANCE"
        g_id = create_grievance(
            conversation_id=body.conversation_id,
            category=cat,
            description=body.description,
            status="draft",
        ) or "grievance-draft-demo"

        # Formulate structured summary
        summary_text = (
            f"Grievance Category: {cat}\n"
            f"Issue Details: {body.description}\n"
            f"Preparation Status: Summary generated successfully for formal submission."
        )

        steps = [
            "1. Review the generated complaint summary for accuracy.",
            "2. Attach supporting documents (passbook, loan receipts, membership card).",
            "3. Submit formal complaint copy to the District Deputy Registrar (DDR) of Cooperative Societies or PACS Managing Director.",
            "4. Obtain acknowledgment receipt from the official registrar desk.",
        ]

        disclaimer_note = (
            "NOTICE: Complaint summary prepared for official submission. "
            "Please present this structured copy to your local District Registrar or PACS office for official processing."
        )

        return GrievanceSummaryResponse(
            grievance_id=g_id,
            category=cat,
            description=body.description,
            summary=summary_text,
            status="draft",
            suggested_next_steps=steps,
            disclaimer=disclaimer_note,
            source_url="https://cooperatives.maharashtra.gov.in",
        )

    except Exception as exc:
        logger.exception("Error creating grievance summary: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unable to process grievance request.",
        ) from exc


@router.post(
    "/handoff",
    response_model=HandoffResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create human handoff assistance record for local PACS desk",
)
async def create_human_handoff(body: HandoffCreateRequest) -> HandoffResponse:
    """
    Creates a structured citizen assistance handoff record for local PACS facilitation.
    - Optionally translates the citizen description into officer language via Bhashini NMT.
    - Persists record with masked contact info into grievances table.
    - Returns deterministic reference code, formatted slip data, and QR payload.
    """
    try:
        citizen_lang = (body.language or "mr").strip().lower().split("-")[0]
        officer_lang = (body.target_officer_language or "en").strip().lower().split("-")[0]

        ref_code = _generate_pacs_reference_code()
        created_at_iso = datetime.now(timezone.utc).isoformat()

        # Build concise officer-facing summary
        raw_issue = body.description.strip()
        translated_summary = None
        translation_status = "same_language"

        if citizen_lang != officer_lang:
            bhashini = BhashiniProvider()
            if bhashini.is_configured:
                try:
                    # Translate issue description using Bhashini NMT
                    trans_res = await bhashini.translate_text(
                        text=raw_issue[:600],
                        source_lang=citizen_lang,
                        target_lang=officer_lang,
                    )
                    if trans_res and trans_res.strip():
                        translated_summary = trans_res.strip()
                        translation_status = "translated"
                    else:
                        translated_summary = raw_issue
                        translation_status = "untranslated_fallback"
                except Exception as nmt_exc:
                    logger.warning("[HANDOFF_NMT] Translation exception, falling back to original text: %s", nmt_exc)
                    translated_summary = raw_issue
                    translation_status = "untranslated_fallback"
            else:
                translated_summary = raw_issue
                translation_status = "untranslated_fallback"
        else:
            translated_summary = raw_issue
            translation_status = "same_language"

        # Call repository to persist grievance
        g_id = create_grievance(
            conversation_id=body.conversation_id,
            category=body.category,
            description=raw_issue,
            status="submitted",
            pacs_name=body.pacs_name,
            citizen_name=body.citizen_name,
            citizen_phone=body.citizen_phone,
            ai_guidance=body.ai_guidance,
            priority=body.priority or "medium",
            reference_code=ref_code,
            citizen_language=citizen_lang,
            translated_summary=translated_summary,
            source_citations=body.source_citations or [],
        )

        if not g_id:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Database failed to record assistance handoff.",
            )

        # Prepare formatted sources for slip
        formatted_sources: list[str] = []
        if body.source_citations:
            for s in body.source_citations:
                if isinstance(s, dict):
                    t = s.get("title") or s.get("source_name")
                    if t:
                        formatted_sources.append(str(t))
                elif isinstance(s, str) and s.strip():
                    formatted_sources.append(s.strip())

        masked_c_name = mask_citizen_name(body.citizen_name)
        masked_c_phone = mask_citizen_phone(body.citizen_phone)

        # Build clean slip data
        display_pacs = body.pacs_name or "Local PACS (Unspecified)"
        qr_url = f"https://sahkaarsetu.gov.in/verify/slip?ref={ref_code}&pacs={display_pacs}&cat={body.category}"

        slip_data = AssistanceSlipData(
            header="SAHKAARSETU PACS ASSISTANCE REFERENCE SLIP",
            reference_code=ref_code,
            created_at=created_at_iso,
            pacs_name=display_pacs,
            village=body.village,
            category=body.category,
            citizen_masked_name=masked_c_name,
            citizen_phone_masked=masked_c_phone,
            citizen_language=citizen_lang,
            officer_language=officer_lang,
            original_query=raw_issue,
            officer_translated_note=translated_summary or raw_issue,
            ai_guidance_summary=body.ai_guidance or "Guidance facilitated by SahkaarSetu.",
            sources=formatted_sources,
            qr_payload=qr_url,
            disclaimer=FACILITATION_DISCLAIMER,
        )

        return HandoffResponse(
            success=True,
            grievance_id=str(g_id),
            reference_code=ref_code,
            category=body.category,
            pacs_name=body.pacs_name,
            village=body.village,
            citizen_masked_name=masked_c_name,
            citizen_phone_masked=masked_c_phone,
            citizen_language=citizen_lang,
            officer_language=officer_lang,
            original_description=raw_issue,
            translated_summary=translated_summary,
            translation_status=translation_status,
            ai_guidance=body.ai_guidance,
            source_citations=body.source_citations or [],
            slip_data=slip_data,
            disclaimer=FACILITATION_DISCLAIMER,
            created_at=created_at_iso,
        )

    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Unexpected error creating assistance handoff: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unable to process assistance handoff request.",
        ) from exc


@router.get("/{grievance_id}", response_model=GrievanceSummaryResponse)
async def fetch_grievance(grievance_id: str) -> GrievanceSummaryResponse:
    """
    Retrieve grievance record by ID.
    """
    record = get_grievance(grievance_id)
    if not record:
        # Return structured placeholder if database is unpopulated
        return GrievanceSummaryResponse(
            grievance_id=grievance_id,
            category="GRIEVANCE",
            description="Cooperative dispute summary",
            summary="Grievance record retrieved.",
            status="draft",
            suggested_next_steps=[
                "Verify details with official District Registrar.",
            ],
            disclaimer="Complaint summary prepared for official submission.",
            source_url="https://cooperatives.maharashtra.gov.in",
        )

    return GrievanceSummaryResponse(
        grievance_id=str(record.get("id")),
        category=record.get("category", "GRIEVANCE"),
        description=record.get("description", ""),
        summary=f"Grievance Category: {record.get('category')}\nDescription: {record.get('description')}",
        status=record.get("status", "draft"),
        suggested_next_steps=[
            "1. Submit physical/digital copy to District Deputy Registrar.",
            "2. Track case status using local receipt ID.",
        ],
        disclaimer="Complaint summary prepared for official submission.",
        source_url="https://cooperatives.maharashtra.gov.in",
    )


@router.get("/{grievance_id}/summary", response_model=GrievanceSummaryResponse)
async def fetch_grievance_summary(grievance_id: str) -> GrievanceSummaryResponse:
    """
    Retrieve structured complaint preparation summary.
    """
    return await fetch_grievance(grievance_id)
